[workspace]
authors = ["Amogh Agarwal <amoghagarwal2000@gmail.com>"]
channels = ["conda-forge"]
name = "Albumizer"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
install-insightface = "pip install insightface"
install-dependencies = { depends_on = ["install", "install-insightface"] }
swap = "python face_swapper.py $@"

[dependencies]
python = ">=3.13.0"
numpy = ">=2.3.0,<3"
pytorch = ">=2.7.0,<3"
pillow = ">=11.2.1,<12"
transformers = ">=4.52.4,<5"
diffusers = ">=0.27.0,<1"
accelerate = ">=0.27.0,<1"
safetensors = ">=0.4.2,<1"
opencv = ">=4.11.0,<5"
requests = ">=2.32.4,<3"
tqdm = ">=4.67.1,<5"
pip = ">=25.1.1,<26"

